server:
  port: 8884
spring:
  application:
    name: notification-service
  config:
    import: optional:file:.env[.properties], optional:file:../.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/db_notification
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5     # Gửi heartbeat mỗi 5s (mặc định 30s)
    lease-expiration-duration-in-seconds: 10 # Hết hạn sau 10s không có heartbeat
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

