server:
  port: 8881
spring:
  application:
    name: auth-service
  config:
    import: optional:file:.env[.properties], optional:file:../.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 86400000
  refresh-token-expiration: 604800000

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5     # Gửi heartbeat mỗi 5s (mặc định 30s)
    lease-expiration-duration-in-seconds: 10 # Hết hạn sau 10s không có heartbeat
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

